[project]
name = "agent-ia-veille-nba"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "stevkouakam", email = "144498156+stevkouakam@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.19.1",
    "fastapi>=0.141.1",
    "langgraph>=1.2.11",
    "nba-api>=1.11.4",
    "psycopg2-binary>=2.9.12",
    "python-telegram-bot>=22.8",
    "sqlalchemy>=2.0.52",
]

[project.scripts]
agent-ia-veille-nba = "agent_ia_veille_nba:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "black>=26.5.1",
    "mypy>=2.3.1",
    "pre-commit>=4.6.2",
    "pytest>=9.1.1",
    "ruff>=0.16.4",
]

[[tool.mypy.overrides]]
module = "nba_api.*"
ignore_missing_imports = true

[tool.black]
target-version = ["py313"]
