"""create games table

Revision ID: 5bb91c1c773a
Revises: 
Create Date: 2026-08-27 00:29:28.303957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bb91c1c773a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.String(length=20), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('home_team', sa.String(length=3), nullable=False),
    sa.Column('away_team', sa.String(length=3), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=False),
    sa.Column('away_score', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'LIVE', 'FINAL', name='game_status'), nullable=False),
    sa.Column('status_text', sa.String(length=50), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('game_clock', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_game_id'), 'games', ['game_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_games_game_id'), table_name='games')
    op.drop_table('games')
    # ### end Alembic commands ###

    # Postgres ENUM types are database-level objects, not owned by the
    # table — drop_table() alone leaves this one behind, so a later
    # upgrade() fails trying to re-create it. Manual addition (not
    # autogenerated) to keep this migration actually reversible.
    sa.Enum(name="game_status").drop(op.get_bind(), checkfirst=True)
